CREATE TABLE STUDENT(
student_id BIGINT primary key auto_increment,
student_Name varchar(10)
)
CREATE TABLE PHONE(
phone_id BIGINT primary key auto_increment,
phone_type varchar(10),
phone_Number varchar(10)
)
CREATE TABLE STUDENT_PHONE(
STUDENT_ID BIGINT,
PHONE_ID BIGINT
)
ALTER TABLE STUDENT_PHONE
ADD CONSTRAINT FKr12
FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT

ALTER TABLE STUDENT_PHONE
ADD CONSTRAINT FKr211
FOREIGN KEY(PHONE_ID) REFERENCES PHONE